# _quarto.yml
project:
  type: website
  
  output-dir: docs
  render:
    - "index.qmd"  # index/landing page
    - "about.qmd"  # about page
    - "now.qmd"    # now page
    - "pages/"     # page files
    - "!posts/"    # don't render blog posts
    
    #- "!pages/"   # to NOT render pages in this dir
    #- "**/*.qmd"  # to render all pages
  
  preview: 
    port: 1909

website:
  #title: ""                        # omitted
  #site-url: https://yoursite.com   # needed for rss feed
  #description: ""                  # optional

  #google-analytics: <Insert your ID here> # if you colelct google data
  #cookie-consent: true             # if you are collecting cookies
  navbar:
    left: # left side of navbar
      - href: index.qmd             # index/home page
      
        text: "My Name or Site Title" # home page title (instead of title:)
      - href: now.qmd               # my now page
        text: Now                   # now page title
      
      # optional about me; comment out it not desired
      - href: about.qmd             # about page
        text: About                 # about page title

      # optional resume; comment out it not desired
      - href: files/resume.pdf      # pdf file
        text: Resume                 # resume page title
        
      # pages without a dropdown
      - href: pages/project/index.qmd       # projects listing page
        text: "Project Title"       # page text
      
      # pages with a dropdown
      - text: "Project Title w/DD"  # page text
        menu: 
          - pages/project/page01.qmd        # the first page
#          - pages/othername.qmd    # the second page


    right: # right side of navbar 
      - icon: github
        href: https://mygithub.com/
      - icon: linkedin
        href: https://www.linkedin.com/school/claremont-mckenna-college/posts/?feedView=all
      - icon: twitter-x
        href: https://x.com/CMCnews
      - icon: bluesky
        href: https://bsky.app/profile/cmc.edu
#      - icon: rss
#        href: blog.xml
        
# format and style
format:
  html:
    theme:
      light: 
        - cosmo          # base theme 
        - custom.scss    # custom scss
      dark: 
        - cosmo          # base theme 
        - custom.scss    # Same file, uses [data-theme="dark"]
